### ISSUE TITLE
Voso configuration

### ISSUE THREAD

**Issue by jim3692** [revoltchat/self-hosted#15]
How do I add vortex to compose?

I tried adding this but I am getting `{error: 1011, message: 'Internal Server Error'}` in the browser console when I try to call someone

```
  voso:
    image: revoltchat/vortex:0.3.0-alpha.1
    ports:
      - "8080:8080"
      - "10000-10100/tcp"
      - "10000-10100/udp"
    environment:
      - WS_URL=ws://<my_pc_ip>:8080
      - MANAGE_TOKEN=CHANGEME
      - RTC_IPS=<my_pc_ip>
      - RTC_MIN_PORT=10000
      - RTC_MAX_PORT=10100
    restart: always
```
