### ISSUE TITLE
How to edit Revolt.toml on Docker?

### ISSUE THREAD

**Issue by fvlasie** [revoltchat/self-hosted#87]
I can't find the Revolt.toml file in any of the docker containers. Does anyone know how to edit Revolt.toml on a docker deployment? Thank you!

_Originally posted by @fvlasie in https://github.com/revoltchat/self-hosted/issues/82#issuecomment-2188215277_

**Comment by fvlasie** [comment]
I am trying to solve the problem of url: "ws://local.revolt.chat/ws"
showing in console.

**Comment by liqingyou** [comment]
same

**Comment by jquiaios** [comment]
I had the same problem and here is how I could make it work.

You need to download the file [Revolt.toml](https://github.com/revoltchat/backend/blob/main/crates/core/config/Revolt.toml) and put it at the same level as the `docker-compose.yml` file.
If you host revolt on an external server, you need to modify your Revolt.toml file to adapt all your URLs.

After that, you modify the `docker-compose,yml` file to add this Revolt.toml file as a volume for both containers `api` and `events`, something like this:
```
# API server (delta)
api:
  image: ghcr.io/revoltchat/server:latest
  env_file: .env
  depends_on:
    - database
    - redis
    - caddy
  restart: always
  volumes:
    - ./Revolt.toml:/Revolt.toml

# Events service (quark)
events:
  image: ghcr.io/revoltchat/bonfire:latest
  env_file: .env
  depends_on:
    - database
    - redis
    - caddy
  restart: always
  volumes:
    - ./Revolt.toml:/Revolt.toml
```

Then you `docker compose up -d` to restart those two containers, and you should be good.
